config/routes.rb
require 'sidekiq/web'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitolite.repos_path,
    upload_pack:  Gitlab.config.gitolite.upload_pack,
    receive_pack: Gitlab.config.gitolite.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.-]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_update
        put :project_teams_update
        delete :remove_project
      end
    end
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, except: [:new, :create] do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end
  end

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"


  #
  # Groups Area
  #
  resources :groups, constraints: { id: /[^\/]+/ }, only: [:show] do
    member do
      get :issues
      get :merge_requests
      get :search
      get :people
      post :team_members
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :tree,    only: [:show, :edit, :update], constraints: {id: /.+/}
    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare",
                    :via => [:get, :post], constraints: {from: /.+/, to: /.+/}

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "stats"
        get "archive"
      end
    end

    resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [] do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :ci_status
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end


    resources :team, controller: 'team_members', only: [:index]
    resources :milestones, except: [:destroy]
    resources :labels, only: [:index]
    resources :issues, except: [:destroy] do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :team_members do
      collection do

        # Used for import team
        # from another project
        get :import
        post :apply_import
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/models/repository.rb
class Repository
  # Repository directory name with namespace direcotry
  # Examples:
  #   gitlab/gitolite
  #   diaspora
  #
  attr_accessor :path_with_namespace

  # Grit repo object
  attr_accessor :repo

  # Default branch in the repository
  attr_accessor :root_ref

  def initialize(path_with_namespace, root_ref = 'master')
    @root_ref = root_ref || "master"
    @path_with_namespace = path_with_namespace

    # Init grit repo object
    repo
  end

  def raw
    repo
  end

  def path_to_repo
    @path_to_repo ||= File.join(Gitlab.config.gitolite.repos_path, "#{path_with_namespace}.git")
  end

  def repo
    @repo ||= Grit::Repo.new(path_to_repo)
  end

  def commit(commit_id = nil)
    Commit.find_or_first(repo, commit_id, root_ref)
  end

  def fresh_commits(n = 10)
    Commit.fresh_commits(repo, n)
  end

  def commits_with_refs(n = 20)
    Commit.commits_with_refs(repo, n)
  end

  def commits_since(date)
    Commit.commits_since(repo, date)
  end

  def commits(ref, path = nil, limit = nil, offset = nil)
    Commit.commits(repo, ref, path, limit, offset)
  end

  def last_commit_for(ref, path = nil)
    commits(ref, path, 1).first
  end

  def commits_between(from, to)
    Commit.commits_between(repo, from, to)
  end

  def has_post_receive_file?
    !!hook_file
  end

  def valid_post_receive_file?
    valid_hook_file == hook_file
  end

  def valid_hook_file
    @valid_hook_file ||= File.read(Rails.root.join('lib', 'hooks', 'post-receive'))
  end

  def hook_file
    @hook_file ||= begin
                     hook_path = File.join(path_to_repo, 'hooks', 'post-receive')
                     File.read(hook_path) if File.exists?(hook_path)
                   end
  end

  # Returns an Array of branch names
  def branch_names
    repo.branches.collect(&:name).sort
  end

  # Returns an Array of Branches
  def branches
    repo.branches.sort_by(&:name)
  end

  # Returns an Array of tag names
  def tag_names
    repo.tags.collect(&:name).sort.reverse
  end

  # Returns an Array of Tags
  def tags
    repo.tags.sort_by(&:name).reverse
  end

  # Returns an Array of branch and tag names
  def ref_names
    [branch_names + tag_names].flatten
  end

  def heads
    @heads ||= repo.heads
  end

  def tree(fcommit, path = nil)
    fcommit = commit if fcommit == :head
    tree = fcommit.tree
    path ? (tree / path) : tree
  end

  def has_commits?
    !!commit
  rescue Grit::NoSuchPathError
    false
  end

  def empty?
    !has_commits?
  end

  # Discovers the default branch based on the repository's available branches
  #
  # - If no branches are present, returns nil
  # - If one branch is present, returns its name
  # - If two or more branches are present, returns the one that has a name
  #   matching root_ref (default_branch or 'master' if default_branch is nil)
  def discover_default_branch
    if branch_names.length == 0
      nil
    elsif branch_names.length == 1
      branch_names.first
    else
      branch_names.select { |v| v == root_ref }.first
    end
  end

  # Archive Project to .tar.gz
  #
  # Already packed repo archives stored at
  # app_root/tmp/repositories/project_name/project_name-commit-id.tag.gz
  #
  def archive_repo(ref)
    ref = ref || self.root_ref
    commit = self.commit(ref)
    return nil unless commit

    # Build file path
    file_name = self.path_with_namespace + "-" + commit.id.to_s + ".tar.gz"
    storage_path = Rails.root.join("tmp", "repositories")
    file_path = File.join(storage_path, file_name)

    # Put files into a directory before archiving
    prefix = self.path_with_namespace + "/"

    # Create file if not exists
    unless File.exists?(file_path)
      FileUtils.mkdir_p storage_path
      file = self.repo.archive_to_file(ref, prefix,  file_path)
    end

    file_path
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @activities = @repository.commits_with_refs(20)
  end

  def branches
    @branches = @repository.branches
  end

  def tags
    @tags = @repository.tags
  end

  def stats
    @stats = Gitlab::GitStats.new(@repository.raw, @repository.root_ref)
    @graph = @stats.graph
  end

  def archive
    unless can?(current_user, :download_code, @project)
      render_404 and return
    end


    file_path = @repository.archive_repo(params[:ref])

    if file_path
      # Send file to user
      send_file file_path
    else
      render_404
    end
  end
end

app/views/repositories/_branch.html.haml
- commit = Commit.new(branch.commit)
- commit = CommitDecorator.decorate(commit)
%tr
  %td
    = link_to project_commits_path(@project, branch.name) do
      - if @project.protected_branch? branch.name
        %i.icon-lock
      - else
        %i.icon-unlock
      %strong= truncate(branch.name, length: 60)
      - if branch.name == @repository.root_ref
        %span.label default
  %td
    = link_to project_commit_path(@project, commit.id), class: 'commit_short_id' do
      = commit.short_id
    = image_tag gravatar_icon(commit.author_email), class: "avatar s16"
    %span.light
      = gfm escape_once(truncate(commit.title, length: 40))
    %span
      = time_ago_in_words(commit.committed_date)
      ago
  %td
    - if can? current_user, :download_code, @project
      = link_to archive_project_repository_path(@project, ref: branch.name) do
        %i.icon-download-alt
        Download

app/views/repositories/_feed.html.haml
- commit = update
- commit = CommitDecorator.new(commit)
%tr
  %td
    = link_to project_commits_path(@project, commit.head.name) do
      %strong
        = commit.head.name
      - if @project.root_ref?(commit.head.name)
        %span.label default

  %td
    %div
      = link_to project_commits_path(@project, commit.id) do
        %code= commit.short_id
      = image_tag gravatar_icon(commit.author_email), class: "", width: 16
      = gfm escape_once(truncate(commit.title, length: 40))
  %td
    %span.right.cgray
      = time_ago_in_words(commit.committed_date)
      ago

app/views/repositories/_filter.html.haml
%ul.nav.nav-pills.nav-stacked
  = nav_link(path: 'repositories#show') do
    = link_to 'Recent', project_repository_path(@project)
  = nav_link(path: 'protected_branches#index') do
    = link_to project_protected_branches_path(@project) do
      Protected
      %i.icon-lock
  = nav_link(path: 'repositories#branches') do
    = link_to 'All branches', branches_project_repository_path(@project)

app/views/repositories/_head.html.haml
= render "projects/project_head"

app/views/repositories/branches.html.haml
= render "commits/head"
.row
  .span3
    = render "filter"
  .span9
    - unless @branches.empty?
      %table
        %thead
          %tr
            %th Name
            %th Last commit
            %th
        %tbody
          - @branches.each do |branch|
            = render "repositories/branch", branch: branch

app/views/repositories/show.html.haml
= render "commits/head"
.row
  .span3
    = render "filter"
  .span9
    %table
      %thead
        %tr
          %th Name
          %th Last commit
          %th
      - @activities.each do |update|
        = render "repositories/branch", branch: update.head

app/views/repositories/stats.html.haml
= render "commits/head"
.row
  .span5
    %h4
      Stats:
    %p
      %b Total commits:
      %span= @stats.commits_count
    %p
      %b Total files in #{@repository.root_ref}:
      %span= @stats.files_count
    %p
      %b Authors:
      %span= @stats.authors_count

    %br
    %div#activity-chart
  .span7
    %h4 Top 50 Committers:
    %ol.styled
      - @stats.authors[0...50].each do |author|
        %li
          = image_tag gravatar_icon(author.email, 16), class: 'avatar s16'
          = author.name
          %small.light= author.email
          .right
            = author.commits


:javascript
  $(function(){
    var labels = [#{@graph.labels.to_json}];
    var commits = [#{@graph.commits.join(', ')}];
    var r = Raphael('activity-chart');
    r.text(160, 10, "Commit activity for last #{@graph.weeks} weeks").attr({ font: "13px sans-serif" });
    r.barchart(
      10, 10, 400, 160,
      [commits],
      {colors:["#456"]}
    ).label(labels, true);
  })

app/views/repositories/tags.html.haml
= render "commits/head"
- unless @tags.empty?
  %table
    %thead
      %tr
        %th Name
        %th Last commit
        %th
    - @tags.each do |tag|
      - commit = Commit.new(tag.commit)
      - commit = CommitDecorator.decorate(commit)
      %tr
        %td
          %strong
            = link_to project_commits_path(@project, tag.name), class: "" do
              %i.icon-tag
              = tag.name
          %small.light= truncate(tag.message || '', length: 70)
        %td
          = image_tag gravatar_icon(commit.author_email), class: "avatar s16"
          = link_to project_commit_path(@project, commit.id), class: 'commit_short_id' do
            = commit.short_id
          %span.light
            = time_ago_in_words(commit.committed_date)
            ago
        %td
          - if can? current_user, :download_code, @project
            = link_to archive_project_repository_path(@project, ref: tag.name) do
              %i.icon-download-alt
              Download

- else
  %h3.nothing_here_message
    Repository has no tags yet.
    %br
    %small
      Use git tag command to add a new one:
      %br
      %span.monospace git tag -a v1.4 -m 'version 1.4'