config/routes.rb
require 'sidekiq/web'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitolite.repos_path,
    upload_pack:  Gitlab.config.gitolite.upload_pack,
    receive_pack: Gitlab.config.gitolite.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.-]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_update
        put :project_teams_update
        delete :remove_project
      end
    end
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, except: [:new, :create] do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, only: [:edit, :update, :destroy]
    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end
    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end
  end

  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard"                => "dashboard#index"
  get "dashboard/issues"         => "dashboard#issues"
  get "dashboard/merge_requests" => "dashboard#merge_requests"


  #
  # Groups Area
  #
  resources :groups, constraints: { id: /[^\/]+/ }, only: [:show] do
    member do
      get :issues
      get :merge_requests
      get :search
      get :people
      post :team_members
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-\/]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      get "wall"
      get "graph"
      get "files"
    end

    resources :tree,    only: [:show, :edit, :update], constraints: {id: /.+/}
    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /.+/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :blob,    only: [:show], constraints: {id: /.+/}
    match "/compare/:from...:to" => "compare#show", as: "compare",
                    :via => [:get, :post], constraints: {from: /.+/, to: /.+/}

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "stats"
        get "archive"
      end
    end

    resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resources :deploy_keys
    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [] do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :ci_status
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end


    resources :team, controller: 'team_members', only: [:index]
    resources :milestones, except: [:destroy]
    resources :labels, only: [:index]
    resources :issues, except: [:destroy] do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end

    resources :team_members do
      collection do

        # Used for import team
        # from another project
        get :import
        post :apply_import
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: namespaces
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  path       :string(255)      not null
#  owner_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  type       :string(255)
#

class Group < Namespace
  def add_users_to_project_teams(user_ids, project_access)
    UsersProject.add_users_into_projects(
      projects.map(&:id),
      user_ids,
      project_access
    )
  end

  def users
    users = User.joins(:users_projects).where(users_projects: {project_id: project_ids})
    users = users << owner
    users.uniq
  end

  def human_name
    name
  end

  def truncate_teams
    UsersProject.truncate_teams(project_ids)
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  private_flag           :boolean          default(TRUE), not null
#  creator_id             :integer
#  default_branch         :string(255)
#  issues_enabled         :boolean          default(TRUE), not null
#  wall_enabled           :boolean          default(TRUE), not null
#  merge_requests_enabled :boolean          default(TRUE), not null
#  wiki_enabled           :boolean          default(TRUE), not null
#  namespace_id           :integer
#

require "grit"

class Project < ActiveRecord::Base
  include Gitolited

  class TransferError < StandardError; end

  attr_accessible :name, :path, :description, :default_branch, :issues_enabled,
                  :wall_enabled, :merge_requests_enabled, :wiki_enabled, :public, as: [:default, :admin]

  attr_accessible :namespace_id, :creator_id, as: :admin

  attr_accessor :error_code

  # Relations
  belongs_to :group, foreign_key: "namespace_id", conditions: "type = 'Group'"
  belongs_to :namespace

  belongs_to :creator,
    class_name: "User",
    foreign_key: "creator_id"

  has_many :users,          through: :users_projects
  has_many :events,         dependent: :destroy
  has_many :merge_requests, dependent: :destroy
  has_many :issues,         dependent: :destroy, order: "closed, created_at DESC"
  has_many :milestones,     dependent: :destroy
  has_many :users_projects, dependent: :destroy
  has_many :notes,          dependent: :destroy
  has_many :snippets,       dependent: :destroy
  has_many :deploy_keys,    dependent: :destroy, foreign_key: "project_id", class_name: "Key"
  has_many :hooks,          dependent: :destroy, class_name: "ProjectHook"
  has_many :wikis,          dependent: :destroy
  has_many :protected_branches, dependent: :destroy
  has_one :last_event, class_name: 'Event', order: 'events.created_at DESC', foreign_key: 'project_id'
  has_one :gitlab_ci_service, dependent: :destroy

  delegate :name, to: :owner, allow_nil: true, prefix: true

  # Validations
  validates :creator, presence: true
  validates :description, length: { within: 0..2000 }
  validates :name, presence: true, length: { within: 0..255 },
            format: { with: Gitlab::Regex.project_name_regex,
                      message: "only letters, digits, spaces & '_' '-' '.' allowed. Letter should be first" }
  validates :path, presence: true, length: { within: 0..255 },
            format: { with: Gitlab::Regex.path_regex,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :issues_enabled, :wall_enabled, :merge_requests_enabled,
            :wiki_enabled, inclusion: { in: [true, false] }

  validates_uniqueness_of :name, scope: :namespace_id
  validates_uniqueness_of :path, scope: :namespace_id

  validate :check_limit, :repo_name

  # Scopes
  scope :without_user, ->(user)  { where("id NOT IN (:ids)", ids: user.authorized_projects.map(&:id) ) }
  scope :not_in_group, ->(group) { where("id NOT IN (:ids)", ids: group.project_ids ) }
  scope :in_namespace, ->(namespace) { where(namespace_id: namespace.id) }
  scope :sorted_by_activity, ->() { order("(SELECT max(events.created_at) FROM events WHERE events.project_id = projects.id) DESC") }
  scope :personal, ->(user) { where(namespace_id: user.namespace_id) }
  scope :joined, ->(user) { where("namespace_id != ?", user.namespace_id) }
  scope :public, where(public: true)

  class << self
    def abandoned
      project_ids = Event.select('max(created_at) as latest_date, project_id').
        group('project_id').
        having('latest_date < ?', 6.months.ago).map(&:project_id)

      where(id: project_ids)
    end

    def with_push
      includes(:events).where('events.action = ?', Event::Pushed)
    end

    def active
      joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
    end

    def search query
      where("projects.name LIKE :query OR projects.path LIKE :query", query: "%#{query}%")
    end

    def find_with_namespace(id)
      if id.include?("/")
        id = id.split("/")
        namespace = Namespace.find_by_path(id.first)
        return nil unless namespace

        where(namespace_id: namespace.id).find_by_path(id.second)
      else
        where(path: id, namespace_id: nil).last
      end
    end

    def access_options
      UsersProject.access_roles
    end
  end

  def team
    @team ||= Team.new(self)
  end

  def repository
    if path
      @repository ||= Repository.new(path_with_namespace, default_branch)
    else
      nil
    end
  rescue Grit::NoSuchPathError
    nil
  end

  def git_error?
    error_code == :gitolite
  end

  def saved?
    id && valid?
  end

  def check_limit
    unless creator.can_create_project?
      errors[:base] << ("Your own projects limit is #{creator.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Can't check your ability to create project")
  end

  def repo_name
    denied_paths = %w(gitolite-admin admin dashboard groups help profile projects search)

    if denied_paths.include?(path)
      errors.add(:path, "like #{path} is not allowed")
    end
  end

  def to_param
    if namespace
      namespace.path + "/" + path
    else
      path
    end
  end

  def web_url
    [Gitlab.config.gitlab.url, path_with_namespace].join("/")
  end

  def build_commit_note(commit)
    notes.new(commit_id: commit.id, noteable_type: "Commit")
  end

  def last_activity
    last_event
  end

  def last_activity_date
    last_event.try(:created_at) || updated_at
  end

  def project_id
    self.id
  end

  def issues_labels
    issues.tag_counts_on(:labels)
  end

  def services
    [gitlab_ci_service].compact
  end

  def gitlab_ci?
    gitlab_ci_service && gitlab_ci_service.active
  end

  # For compatibility with old code
  def code
    path
  end

  def items_for entity
    case entity
    when 'issue' then
      issues
    when 'merge_request' then
      merge_requests
    end
  end

  def send_move_instructions
    self.users_projects.each do |member|
      Notify.delay.project_was_moved_email(member.id)
    end
  end

  def owner
    if namespace
      namespace_owner
    else
      creator
    end
  end

  def team_member_by_name_or_email(name = nil, email = nil)
    user = users.where("name like ? or email like ?", name, email).first
    users_projects.where(user: user) if user
  end

  # Get Team Member record by user id
  def team_member_by_id(user_id)
    users_projects.find_by_user_id(user_id)
  end

  def transfer(new_namespace)
    Project.transaction do
      old_namespace = namespace
      self.namespace = new_namespace

      old_dir = old_namespace.try(:path) || ''
      new_dir = new_namespace.try(:path) || ''

      old_repo = if old_dir.present?
                   File.join(old_dir, self.path)
                 else
                   self.path
                 end

      if Project.where(path: self.path, namespace_id: new_namespace.try(:id)).present?
        raise TransferError.new("Project with same path in target namespace already exists")
      end

      Gitlab::ProjectMover.new(self, old_dir, new_dir).execute

      gitolite.move_repository(old_repo, self)

      save!
    end
  rescue Gitlab::ProjectMover::ProjectMoveError => ex
    raise Project::TransferError.new(ex.message)
  end

  def name_with_namespace
    @name_with_namespace ||= begin
                               if namespace
                                 namespace.human_name + " / " + name
                               else
                                 name
                               end
                             end
  end

  def namespace_owner
    namespace.try(:owner)
  end

  def path_with_namespace
    if namespace
      namespace.path + '/' + path
    else
      path
    end
  end

  # This method will be called after each post receive and only if the provided
  # user is present in GitLab.
  #
  # All callbacks for post receive should be placed here.
  def trigger_post_receive(oldrev, newrev, ref, user)
    data = post_receive_data(oldrev, newrev, ref, user)

    # Create push event
    self.observe_push(data)

    if push_to_branch? ref, oldrev
      # Close merged MR
      self.update_merge_requests(oldrev, newrev, ref, user)

      # Execute web hooks
      self.execute_hooks(data.dup)

      # Execute project services
      self.execute_services(data.dup)
    end

    # Create satellite
    self.satellite.create unless self.satellite.exists?

    # Discover the default branch, but only if it hasn't already been set to
    # something else
    if repository && default_branch.nil?
      update_attributes(default_branch: self.repository.discover_default_branch)
    end
  end

  def push_to_branch? ref, oldrev
    ref_parts = ref.split('/')

    # Return if this is not a push to a branch (e.g. new commits)
    !(ref_parts[1] !~ /heads/ || oldrev == "00000000000000000000000000000000")
  end

  def observe_push(data)
    Event.create(
      project: self,
      action: Event::Pushed,
      data: data,
      author_id: data[:user_id]
    )
  end

  def execute_hooks(data)
    hooks.each { |hook| hook.execute(data) }
  end

  def execute_services(data)
    services.each do |service|

      # Call service hook only if it is active
      service.execute(data) if service.active
    end
  end

  # Produce a hash of post-receive data
  #
  # data = {
  #   before: String,
  #   after: String,
  #   ref: String,
  #   user_id: String,
  #   user_name: String,
  #   repository: {
  #     name: String,
  #     url: String,
  #     description: String,
  #     homepage: String,

app/helpers/groups_helper.rb
module GroupsHelper
  def group_filter_path(entity, options={})
    exist_opts = {
      status: params[:status],
      project_id: params[:project_id],
    }

    options = exist_opts.merge(options)

    case entity
    when 'issue' then
      issues_group_path(@group, options)
    when 'merge_request'
      merge_requests_group_path(@group, options)
    end
  end
end

app/views/groups/_filter.html.haml
= form_tag group_filter_path(entity), method: 'get' do
  %fieldset.dashboard-search-filter
    = search_field_tag "search", params[:search], { placeholder: 'Search', class: 'search-text-input' }
    = button_tag type: 'submit', class: 'btn' do
      %i.icon-search

  %fieldset
    %legend Status:
    %ul.nav.nav-pills.nav-stacked
      %li{class: ("active" if !params[:status])}
        = link_to group_filter_path(entity, status: nil) do
          Open
      %li{class: ("active" if params[:status] == 'closed')}
        = link_to group_filter_path(entity, status: 'closed') do
          Closed
      %li{class: ("active" if params[:status] == 'all')}
        = link_to group_filter_path(entity, status: 'all') do
          All

  %fieldset
    %legend Projects:
    %ul.nav.nav-pills.nav-stacked
      - @projects.each do |project|
        - unless entities_per_project(project, entity).zero?
          %li{class: ("active" if params[:project_id] == project.id.to_s)}
            = link_to group_filter_path(entity, project_id: project.id) do
              = project.name_with_namespace
              %small.right= entities_per_project(project, entity)

  %fieldset
    %hr
    = link_to "Reset", group_filter_path(entity), class: 'btn right'

app/views/groups/_new_group_member.html.haml
= form_for @team_member, as: :team_member, url: team_members_group_path(@group) do |f|
  %fieldset
    %legend= "New Team member(s) for projects in #{@group.name}"

    %h6 1. Choose people you want in the team
    .clearfix
      = f.label :user_ids, "People"
      .input= select_tag(:user_ids, options_from_collection_for_select(User.active.alphabetically, :id, :name), {data: {placeholder: "Select users"}, class: "chosen xxlarge", multiple: true})

    %h6 2. Set access level for them
    .clearfix
      = f.label :project_access, "Project Access"
      .input= select_tag :project_access, options_for_select(Project.access_options, @team_member.project_access), class: "project-access-select chosen"

    .form-actions
      = hidden_field_tag :redirect_to, people_group_path(@group)
      = f.submit 'Add', class: "btn save-btn"

app/views/groups/_new_member.html.haml
= form_for @team_member, as: :team_member, url: project_team_members_path(@project, @team_member) do |f|
  %fieldset
    %legend= "New Team member(s) for #{@project.name}"

    %h6 1. Choose people you want in the team
    .clearfix
      = f.label :user_ids, "People"
      .input= select_tag(:user_ids, options_from_collection_for_select(User.not_in_project(@project).alphabetically, :id, :name), {data: {placeholder: "Select users"}, class: "chosen xxlarge", multiple: true})

    %h6 2. Set access level for them
    .clearfix
      = f.label :project_access, "Project Access"
      .input= select_tag :project_access, options_for_select(Project.access_options, @team_member.project_access), class: "project-access-select chosen"

    .form-actions
      = hidden_field_tag :redirect_to, people_group_path(@group, project_id: @project.id)
      = f.submit 'Add', class: "btn save-btn"

app/views/groups/_people_filter.html.haml
= form_tag people_group_path(@group), method: 'get' do
  %fieldset
    %legend Projects:
    %ul.nav.nav-pills.nav-stacked
      - @projects.each do |project|
        %li{class: ("active" if params[:project_id] == project.id.to_s)}
          = link_to people_group_path(@group, project_id: project.id) do
            = project.name_with_namespace
            %small.right= project.users.count

  %fieldset
    %hr
    = link_to "Reset", people_group_path(@group), class: 'btn right'

app/views/groups/_projects.html.haml
.projects_box
  %h5.title
    Projects
    %small
      (#{projects.count})
    - if can? current_user, :manage_group, @group
      %span.right
        = link_to new_project_path(namespace_id: @group.id), class: "btn very_small info" do
          %i.icon-plus
          New Project
  %ul.well-list
    - if projects.blank?
      %p.nothing_here_message This groups has no projects yet
    - projects.each do |project|
      %li
        = link_to project_path(project), class: dom_class(project) do
          %strong.well-title= truncate(project.name, length: 25)
          %span.arrow
            &rarr;
          %span.last_activity
            %strong Last activity:
            %span= project_last_activity(project)

app/views/groups/issues.html.haml
%h3.page_title
  Issues
  %small (assigned to you)
  %small.right #{@issues.total_count} issues

%hr
.row
  .span3
    = render 'filter', entity: 'issue'
  .span9
    - if @issues.any?
      - @issues.group_by(&:project).each do |group|
        %div.ui-box
          - project = group[0]
          %h5.title
            = link_to_project project
          %ul.well-list.issues_table
            - group[1].each do |issue|
              = render(partial: 'issues/show', locals: {issue: issue})
      %hr
      = paginate @issues, theme: "gitlab"
    - else
      %p.nothing_here_message Nothing to show here

app/views/groups/merge_requests.html.haml
%h3.page_title
  Merge Requests
  %small (authored by or assigned to you)
  %small.right #{@merge_requests.total_count} merge requests

%hr
.row
  .span3
    = render 'filter', entity: 'merge_request'
  .span9
    = render 'shared/merge_requests'

app/views/groups/people.html.haml
.row
  .span3
    = render 'people_filter'
  .span9
    - if can?(current_user, :manage_group, @group)
      = render (@project ? "new_member" : "new_group_member")
    .ui-box
      %h5.title
        Team
        %small
          (#{@users.size})
      %ul.well-list
        - @users.each do |user|
          %li
            = image_tag gravatar_icon(user.email, 16), class: "avatar s16"
            %strong= user.name
            %span.cgray= user.email
            - if @group.owner == user
              %span.btn.btn-small.disabled.right Group Owner

app/views/groups/search.html.haml
= form_tag search_group_path(@group), method: :get, class: 'form-inline' do |f|
  .padded
    = label_tag :search do
      %strong Looking for
    .input
      = search_field_tag :search, params[:search], placeholder: "issue 143", class: "input-xxlarge search-text-input", id: "dashboard_search"
      = submit_tag 'Search', class: "btn primary wide"
- if params[:search].present?
  = render 'search/result'

app/views/groups/show.html.haml
.projects
  .activities.span8
    = render "events/event_last_push", event: @last_push
    = link_to dashboard_path, class: 'btn very_small' do
      &larr; To dashboard
    &nbsp;
    %span.cgray You will only see events from projects in this group
    %hr
    - if @events.any?
      .content_list
    - else
      %p.nothing_here_message Project activity will be displayed here
    .loading.hide
  .side.span4
    = render "projects", projects: @projects
    %div
      %span.rss-icon
        = link_to dashboard_path(:atom, { private_token: current_user.private_token }) do
          = image_tag "rss_ui.png", title: "feed"
          %strong News Feed

    %hr
    .gitlab-promo
      = link_to "Homepage", "http://gitlabhq.com"
      = link_to "Blog", "http://blog.gitlabhq.com"
      = link_to "@gitlabhq", "https://twitter.com/gitlabhq"

:javascript
  $(function(){ Pager.init(20, true); });

app/views/groups/show.js.haml
:plain 
  Pager.append(#{@events.count}, "#{escape_javascript(render(@events))}");